name: Wagtail Hallo CI

on:
  push:
    branches:
      - main
      - 'stable/**'

  pull_request:

jobs:
  check-client:
    name: 🧑‍🚀 preflight (check client)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - id: npm-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('.nvmrc') }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run preflight

  check-server-black:
    name: ⚫ Black (check server)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python black Lint
        uses: psf/black@stable

  check-server-flake8:
    name: 🎱 flake8 (check server)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python flake8 Lint
        uses: py-actions/flake8@v2.0.0

  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9']
        django: ['3.2', '4.0']
        wagtail: ['2.15', '2.16']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-sqlite

  test-postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9']
        django: ['3.2', '4.0']
        wagtail: ['2.15', '2.16']
        postgres: ['10.8']

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/wagtail_hallo
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-postgres
