name: Wagtail Hallo CI

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check-client:
    name: 🧑‍🚀 preflight (check client)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - id: npm-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('.nvmrc') }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run preflight

  check-server-black:
    name: ⚫ Black (check server)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python black Lint
        uses: psf/black@stable

  check-server-flake8:
    name: 🎱 flake8 (check server)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python flake8 Lint
        uses: py-actions/flake8@v2

  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.11']
        django: ['3.2', '4.2']
        wagtail: ['4.0', '4.1', '4.2', '5.0', '5.1', '5.2']
        exclude:
          - wagtail: '4.0'
            python: '3.11'
          - wagtail: '4.0'
            django: '4.2'
          - wagtail: '4.0'
            django: '4.2'
          - wagtail: '4.1'
            django: '4.2'
          - wagtail: '4.2'
            django: '4.2'
        include:
          - wagtail: '5.2'
            django: '5.0'
            python: '3.12'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: python -m pip install tox
      - name: Test
        run: tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-sqlite

  test-postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.11']
        django: ['3.2', '4.2']
        wagtail: ['4.0', '4.1', '4.2', '5.0', '5.1', '5.2']
        postgres: ['12.17', '16.1']
        exclude:
          - wagtail: '4.0'
            python: '3.11'
          - wagtail: '4.0'
            django: '4.2'
          - wagtail: '4.0'
            django: '4.2'
          - wagtail: '4.1'
            django: '4.2'
          - wagtail: '4.2'
            django: '4.2'
        include:
          - wagtail: '5.2'
            django: '5.0'
            postgres: '12.17'
            python: '3.12'
          - wagtail: '5.2'
            django: '5.0'
            postgres: '16.1'
            python: '3.12'

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: python -m pip install tox
      - name: Test
        run: tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/wagtail_hallo
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-postgres
